<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Arquitectura_BACKEND</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="BookStore\api\controllers\" />
    <Folder Include="BookStore\api\middlewares\" />
    <Folder Include="BookStore\api\filters\" />
    <Folder Include="BookStore\application\adapters\" />
    <Folder Include="BookStore\application\workflows\" />
    <Folder Include="BookStore\domain\domainServices\" />
    <Folder Include="BookStore\domain\specifications\" />
    <Folder Include="BookStore\infrastructure\externalServices\" />
    <Folder Include="BookStore\infrastructure\dependencyInjection\" />
    <Folder Include="BookStore\infrastructure\Persistance\queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
  </ItemGroup>

</Project>
